module.exports = {
    cookingLangEN: 'Write a recipe based on these food name to create ingredients and instructions: ',
    cookingWarningLangEN: '```diff\n- EAT AT YOUR OWN RISK -\n```',
    cookingLangID: 'Tulis sebuah nama makanan yang kamu inginkan agar dapat dibuatkan resep bahan-bahannya beserta dengan caranya pembuatannya: ',
    cookingWarningLangID: '```diff\n- RESIKO ATAS MAKANANNYA SILAHKAN ANDA TANGGUNG SENDIRI -\n```',
    color: 'hex color code from: ',
    curie1: 'text-curie-001',
    davinci2code: 'code-davinci-002',
    davinci3: 'text-davinci-003',
    fixCppBug: '##### Fix bugs in the below function\n\n### Buggy C++\n',
    fixCppBugln2: '### Fixed C++\n',
    fixCssBug: '<!-- add this css code to support all browser -->\n<!-- css: -->\n<style>\n',
    fixCssBugln2: '</style>\n\n<!-- after adding prefix: -->\n<!-- css: -->\n<style>\n',
    fixCssBugln2re: '### Fixed CSS\n',
    fixJSBug: '##### Fix bugs in the below function\n\n### Buggy JavaScript\n',
    fixJSBugln2: '### Fixed JavaScript\n',
    fixPythonBug: '##### Fix bugs in the below function\n\n### Buggy Python\n',
    fixPythonBugln2: '### Fixed Python\n',
    fixWaitReply: 'Fixing...',
    generating: 'Generating...',
    moviemoji: 'Convert movie titles into emoji.\n\nBack to the Future: 👨👴🚗🕒 \nBatman: 🤵🦇 \nTransformers: 🚗🤖 \n',
    movieStoryLangEN: 'Storyline of this movie by it\'s titles.\n\nBack to the Future: Marty McFly, a typical American teenager of the Eighties, is accidentally sent back to 1955 in a plutonium-powered DeLorean "time machine" invented by a slightly mad scientist. During his often hysterical, always amazing trip back in time, Marty must make certain his teenage parents-to-be meet and fall in love - so he can get back to the future. \nBatman: Gotham City. Crime boss Carl Grissom (Jack Palance) effectively runs the town but there\'s a new crime fighter in town - Batman (Michael Keaton). Grissom\'s right-hand man is Jack Napier (Jack Nicholson), a brutal man who is not entirely sane... After falling out between the two Grissom has Napier set up with the Police and Napier falls to his apparent death in a vat of chemicals. However, he soon reappears as The Joker and starts a reign of terror in Gotham City. Meanwhile, reporter Vicki Vale (Kim Basinger) is in the city to do an article on Batman. She soon starts a relationship with Batman\'s everyday persona, billionaire Bruce Wayne. \nTransformers: High-school student Sam Witwicky buys his first car, who is actually the Autobot Bumblebee. Bumblebee defends Sam and his girlfriend Mikaela Banes from the Decepticon Barricade, before the other Autobots arrive on Earth. They are searching for the Allspark, and the war on Earth heats up as the Decepticons attack a United States military base in Qatar. Sam and Mikaela are taken by the top-secret agency Sector 7 to help stop the Decepticons, but when they learn the agency also intends to destroy the Autobots, they formulate their own plan to save the world. \n',
    movieStoryLangID: 'Review movie titles.\n\nBack to the Future: Marty McFly, tipikal remaja Amerika pada tahun 80-an, secara tidak sengaja dikirim kembali ke tahun 1955 dalam "mesin waktu" DeLorean bertenaga plutonium yang ditemukan oleh ilmuwan yang sedikit gila. Selama perjalanannya yang sering histeris dan selalu menakjubkan ke masa lalu, Marty harus memastikan calon orang tua remajanya bertemu dan jatuh cinta - agar dia bisa kembali ke masa depan. \nBatman: Kota Gotham. Bos kejahatan Carl Grissom (Jack Palance) secara efektif menjalankan kota tetapi ada pejuang kejahatan baru di kota - Batman (Michael Keaton). Tangan kanan Grissom adalah Jack Napier (Jack Nicholson), seorang pria brutal yang tidak sepenuhnya waras... tong bahan kimia. Namun, dia segera muncul kembali sebagai The Joker dan memulai teror di Kota Gotham. Sementara itu, reporter Vicki Vale (Kim Basinger) sedang berada di kota untuk membuat artikel tentang Batman. Dia segera memulai hubungan dengan persona sehari-hari Batman, miliarder Bruce Wayne. \nTransformers: Siswa sekolah menengah Sam Witwicky membeli mobil pertamanya, yang sebenarnya adalah Autobot Bumblebee. Bumblebee membela Sam dan pacarnya Mikaela Banes dari Decepticon Barricade, sebelum Autobots lainnya tiba di Bumi. Mereka mencari Allspark, dan perang di Bumi memanas saat Decepticons menyerang pangkalan militer Amerika Serikat di Qatar. Sam dan Mikaela dibawa oleh agen rahasia Sektor 7 untuk membantu menghentikan Decepticons, tetapi ketika mereka mengetahui bahwa agen tersebut juga berniat untuk menghancurkan Autobots, mereka menyusun rencana mereka sendiri untuk menyelamatkan dunia. \n',
    translateCN: '将这句话翻译成 ',
    translateEN: 'Translate this sentence into ',
    translateID: 'Terjemahkan kalimat ini menjadi ',
    translateJP: 'この文を翻訳してください ',
    translateRU: 'Переведите это предложение на ',
    translateStr: ': ',
    translating: 'Translating...'
};